//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyORM.Framework.WinScheduleUI.ScheduleJobServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScheduleJobServices.IScheduleJobService")]
    public interface IScheduleJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleJobService/StartNewScheduleJob", ReplyAction="http://tempuri.org/IScheduleJobService/StartNewScheduleJobResponse")]
        void StartNewScheduleJob(MyORM.Framework.ScheduleJob.Store.JobData jobData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleJobService/StartNewScheduleJob", ReplyAction="http://tempuri.org/IScheduleJobService/StartNewScheduleJobResponse")]
        System.Threading.Tasks.Task StartNewScheduleJobAsync(MyORM.Framework.ScheduleJob.Store.JobData jobData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleJobService/GetCurrentRunningJobStatus", ReplyAction="http://tempuri.org/IScheduleJobService/GetCurrentRunningJobStatusResponse")]
        MyORM.Framework.ScheduleJob.Store.RunningJobStatus[] GetCurrentRunningJobStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduleJobService/GetCurrentRunningJobStatus", ReplyAction="http://tempuri.org/IScheduleJobService/GetCurrentRunningJobStatusResponse")]
        System.Threading.Tasks.Task<MyORM.Framework.ScheduleJob.Store.RunningJobStatus[]> GetCurrentRunningJobStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScheduleJobServiceChannel : MyORM.Framework.WinScheduleUI.ScheduleJobServices.IScheduleJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScheduleJobServiceClient : System.ServiceModel.ClientBase<MyORM.Framework.WinScheduleUI.ScheduleJobServices.IScheduleJobService>, MyORM.Framework.WinScheduleUI.ScheduleJobServices.IScheduleJobService {
        
        public ScheduleJobServiceClient() {
        }
        
        public ScheduleJobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScheduleJobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScheduleJobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScheduleJobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartNewScheduleJob(MyORM.Framework.ScheduleJob.Store.JobData jobData) {
            base.Channel.StartNewScheduleJob(jobData);
        }
        
        public System.Threading.Tasks.Task StartNewScheduleJobAsync(MyORM.Framework.ScheduleJob.Store.JobData jobData) {
            return base.Channel.StartNewScheduleJobAsync(jobData);
        }
        
        public MyORM.Framework.ScheduleJob.Store.RunningJobStatus[] GetCurrentRunningJobStatus() {
            return base.Channel.GetCurrentRunningJobStatus();
        }
        
        public System.Threading.Tasks.Task<MyORM.Framework.ScheduleJob.Store.RunningJobStatus[]> GetCurrentRunningJobStatusAsync() {
            return base.Channel.GetCurrentRunningJobStatusAsync();
        }
    }
}
